export const SET_TASK = 'SET_TASK';

export const GET_LOCAL_STORAGE = 'GET_LOCAL_STORAGE';
export const REQUEST_LOCAL_STORAGE_SUCCESS = 'REQUEST_LOCAL_STORAGE_SUCCESS';
export const REQUEST_LOCAL_STORAGE_ERROR = 'REQUEST_LOCAL_STORAGE_ERROR';
