export const SET_TASK = 'SET_TASK';

export const GET_LOCAL_STORAGE = 'GET_LOCAL_STORAGE';
export const REQUEST_LOCAL_STORAGE = 'REQUEST_LOCAL_STORAGE';
export const REQUEST_LOCAL_STORAGE_SUCCEEDED = 'REQUEST_LOCAL_STORAGE_SUCCEEDED';
export const REQUEST_LOCAL_STORAGE_FAILED = 'REQUEST_LOCAL_STORAGE_FAILED';
